version: '3'
services:
  whai-back:
    image: heung27/whai-back:latest
    ports:
      - '80:8081'
    platform: linux/amd64
    environment:
      - USE_PROFILE=real
    depends_on:
      - whai-mysql
      - whai-redis
    networks:
      - whai-net

  whai-mysql:
    image: mysql:8.0.30
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=y2829!
      - MYSQL_USER=y2829
      - MYSQL_PASSWORD=Admin2829!
      - MYSQL_DATABASE=whai
    networks:
      - whai-net

  whai-redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always
    networks:
      - whai-net

networks:
  whai-net:
    driver: bridge
