server:
  address: 0.0.0.0
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://whai-mysql:3306/whai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: y2829
    password: Admin2829!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: whai-redis
    port: 6379